name: Build and Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 7 * * *"

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          #ubuntu-latest,
          #windows-latest,
          macos-latest,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Build
        run: zig build

      - name: Unit Test
        run: zig build test

      - name: Dry run packaging
        run: |
          cd test/monorepo
          ../../zig-out/bin/boxzer http://localhost:8000
          python3 -m http.server 8000 --directory boxzer-out &
          sleep 1

          cd ../workbench/a
          zig fetch --save=b http://localhost:8000/monorepo-0.0.0/b-0.0.0.tar.gz
          zig build

          # clean up server
          jobs -p | xargs kill
